### ISSUE TITLE
Deleting templates and types

### ISSUE THREAD

**Issue by AlanReviews** [usnistgov/MDCS#11]
Is it possible to remove templates and types in the composer If so, how do I delete a template or type in the composer?

**Comment by Guillaume-sousa** [comment]
You can disable them so that they don't appear in the composer anymore.

1) Go in "My Templates":
<img width="942" alt="Screen Shot 2020-10-02 at 9 30 34 AM" src="https://user-images.githubusercontent.com/8738829/94928767-2c4e5700-0492-11eb-800f-4107eea187b1.png">

2) Click on "Disable" on the line of the template you wish to disable:
<img width="1393" alt="Screen Shot 2020-10-02 at 9 30 47 AM" src="https://user-images.githubusercontent.com/8738829/94928808-35d7bf00-0492-11eb-8a6b-ebf67603472b.png">

You can do the same thing with types using the "My Types" menu.

**Comment by AlanReviews** [comment]
That worked. Thank you.
